### PR TITLE
Adds a test

### PR DESCRIPTION
**Pull request by dsblank**
This has a test, which doesn't pass, so I still think that this code has problems. But maybe it is my test.

Please take a look (I use the from_struct method of creating objects... easier than a bunch of code adding each individual attribute).

To run, you can:

```
GRAMPS_RESOURCES=. nosetests3 --pdb gramps/gen/lib/test/place_test.py
```

or more simply:

```
python3 -m nose gramps/gen/lib/test/place_test.py
```

The --pdb flag will stop the test, and put you in the debugger.

If you can, it'd be great to have these kinds of tests on all of your contribs. Thanks!

### CODE REVIEW

**Comment by prculley** [comment]
I'm not quite sure what to do with this.  It appears you are trying to update my master branch, but I thought I was supposed to keep this clean and synced to origin...
Wouldn't this be better placed into my bug9414 branch off of gramps42?
I have not even run anything off the master branch yet, as I am currently running in the Windows AIO environment, have not been able to get the dependencies on my windows system figured out any other way. I'll figure something out on that if I have to...
And then there is the question of testing strategy.  Most of my bugs to date relate to GEDCOM import.  libgedcom  has over 8000 lines of code, and I am currently at a loss on how to even begin using this type of test technique on most of it.  I sure have not found any such code on this, although I'm not sure where to look.  If you example 'test lines per code lines' metric is any kind of average, writing this will be a daunting task.
It seems that for 'import' type testing, we should be constructing **interesting** import files, and then checking the gramps database (look at XML, or ???) to see if the data imported correctly, (or at least not worse than previous versions).  I've been doing this manually via the GUI, but an automated method would seem very useful.

**Comment by prculley** [comment]
So I downloaded your pull as a .patch, got it applied to my bug9414 branch, (although the first part of the patch to place.py didn't work, since the gramps42 branch doesn't have the associated code).
I tried to do your 
 python3 -m nose gramps/gen/lib/test/place_test.py
and got an error "No module named nose".  It doesn't seem to be in the master branch either...
I suspect there are a few assumptions we are not matched up on...

**Comment by dsblank** [comment]
Oh, sorry, yes, that should have been applied to your branch, not your master.

It is really just the one file. Once you put that in the right place, then you use nose. nose is a python library. Or you can run the file directly:

```
python3 gramps/gen/lib/test/place_test.py
```

**Comment by dsblank** [comment]
We can have two kinds of tests: those that run the changed code directly (like the example PR), and a complete GEDCOM import. 

There are complete GEDCOM tests, but only in master. Master is where all the new tests are being created.

You should be able to switch back and forth between master and gramps42. You must be using a git checkout of the code. I can't think of a reason why master wouldn't run, but maybe I am forgetting something.

**Comment by dsblank** [comment]
When you add tests to gramps42, or master, they will run automatically with the push, either to the main repo, or via a PR. You can see the status here:

https://travis-ci.org/gramps-project/gramps/branches

**Comment by prculley** [comment]
So I finally managed to run your proposed test.  And you are right, as written the test fails.  
Initially it failed badly, in part because I have two patches that the test is sort of checking, and this is only one of them.  The other is bug9415 (alt place names get duplicated entries).  I added in the bug9414 patch as well, and it still fails, but not with duplicates.

But the test is trying to do something the code was not originally (or as patched) designed to accomplish.  The original code was designed to merge a PlaceName object loaded into the **place.name** into an already present Place object.  In the process, it checked if the new PlaceName was present, and if not did not merge it into place.alt_names.  The remainder of the merge assumes that the alt_names are correct as present, and so doesn't remove a blank alt_name entry.
Your test has place1, with both a blank place1.name, and with a place1.alt_names[2] as a blank.  The former is correctly ignored by the patch, the latter was not affected and was merged in since we presume alt_names is correct.
If you remove the test's third blank alt_name, then the test passes.

If you want this merge code to be bulletproof, then we should also check BOTH sides of the merge for already existing blank and duplicate alt_names, and clean them up.  But that seems like more of a data correction feature, not what was originally intended.

The test itself will need three merges to check the three possible merge code paths (assuming we don't bulletproof).  The merging of alt_names could be combined in one of the three checks.

Also I found a file in master called merge_test.py in gen.lib.test; it is already performing a few different merges including what appear to be alt_name merges.  I didn't try to figure out exactly what it did, but it seems to have missed the these bugs...

**Comment by dsblank** [comment]
Ok, it sounds like you have a good understanding of what the code is designed to do, and what is needed for a test. This was really just an example of how to write a test.

If you could then, please add version of the test to the PR that will fail before the fix, and pass afterwards. If you want to test for additional things, that of course is great as well.

Thanks again!

**Comment by prculley** [comment]
1) Do I need to create a test for ONLY this bug?  
2) Or is it ok to devise a test that shows up two bugs (in this case) or more, and therefore will not pass until all patches are in place?
3) since some of your testing stuff is master branch, is it sufficient to do testing there, or do I also have to back-port tests to gramps42?
4) Who does porting of patches to master, since I developed in gramps42?
This all started when I had a single GEDCOM that exercised around 5 bugs.  I got told I needed to separate the bugs/patches out.  Just trying to understand the test philosophy here.
I'm off now to look at whatever code you have that tests the GEDCOM import, to see if it can be adapted to my problem.

**Comment by dsblank** [comment]
I have to run now, but with little bugs like this, it is hard to tell by looking what is correct. It would be preferable to have a little test for each PR.

Normally, people work in master, and backport fixes to maintenance releases, if necessary.

**Pull request closed without merging**
